export { default as HeroSection } from './hero-section'
export { default as FeaturesSection } from './features-section'
export { default as HowItWorksSection } from './how-it-works-section'
export { default as PartnersSection } from './partners-section'
export { default as PricingSection } from './pricing-section'
export { default as CTASection } from './cta-section'
export { default as AnimatedSection } from './animated-section'